name: ci
on: 
  workflow_dispatch:
  pull_request: 
    branches:
      - 'main'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12, macos-11]
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Test terminal app window properties
      shell: bash
      run: | 
        set -x
        swift build
        mkdir -p ~/output
        cd .github/scripts
        chmod 777 assert.sh
        chmod 777 terminal-pdubs.sh
        open -a Terminal "$GITHUB_WORKSPACE/.github/scripts/terminal-pdubs.sh"
        ./assert.sh
        ls -la ~/output
        cat ~/output/ci-results.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output ${{ matrix.os }}
        path: ~/output
        if-no-files-found: error


