name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Build release artifacts
      shell: bash
      run: | 
        set -x
        mkdir -p ~/output
        .github/scripts/release.sh
        cd .build/apple/Products/Release
        mv pdubs.tar.gz pdubs.tar.gz.sha256 ~/output
        ls -la ~/output

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output ${{ matrix.os }}
        path: ~/output
        if-no-files-found: error
  release:
    name: release
    runs-on: macos-13
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: |
          npm install @semantic-release/git @semantic-release/changelog -D
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PDUBS_CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PDUBS_CI_TOKEN }}

